[versions]
h2database = "2.4.240"
jackson = "2.20.1"
junit-platform-launcher = "6.0.2"
lombok = "9.2.0"
postgres = "42.7.9"
springboot = "4.0.2"
spring-dependency-plugin = "1.1.7"
springdoc = "3.0.1"
testcontainers = "1.21.4"
wiremock = '3.13.2'

[libraries]
# H2 for an in-memory database
h2database = { module = "com.h2database:h2", version.ref = "h2database" }

# JUnit platform launcher for running JUnit tests
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }

# PostgreSQL for a live database
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# Spring Boot libraries
springboot-resttestclient = { module = 'org.springframework.boot:spring-boot-resttestclient', version.ref = "springboot" }
springboot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springboot" }
springboot-starter-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springboot" }
springboot-starter-liquibase = { module = "org.springframework.boot:spring-boot-starter-liquibase", version.ref = "springboot" }
springboot-starter-restclient = { module = 'org.springframework.boot:spring-boot-starter-restclient', version.ref = 'springboot' }
springboot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot" }
springboot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springboot" }
springboot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc", version.ref = "springboot" }
springboot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springboot" }

# Testcontainers for running PostgreSQL in tests
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

# Springdoc provides swagger docs with support for Spring Web MVC
springdoc-openapi-starter-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# WireMock for mocking HTTP services in tests
wiremock = { module = 'org.wiremock:wiremock-standalone', version.ref = 'wiremock' }

[plugins]
# Lombok
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

# Spring plugins
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependencies = { id = "io.spring.dependency-management", version.ref = "spring-dependency-plugin" }
